### ISSUE TITLE
Stack size computation issue

### ISSUE THREAD

**Issue by Z-Shang** [vstinner/bytecode#68]
For example:
![image](https://user-images.githubusercontent.com/859939/95697119-66d1a400-0c89-11eb-9897-32ee2a46d58d.png)

This will cause a stack underflow, but no error was given until the segfault.
Expecting something like:
![image](https://user-images.githubusercontent.com/859939/95697310-1149c700-0c8a-11eb-94d4-e13dae235bd2.png)

**Comment by MatthieuDartiailh** [comment]
bytecode does not currently perform this kind of validation (which would require to know more about each bytecode than is currently known). I am not sure I would want such validation ran by default but it could be interesting. Feel free to put together a PR, I will be happy to review it.

**Comment by Z-Shang** [comment]
PR created: https://github.com/vstinner/bytecode/pull/69 :)
